version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: invest-ia-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invest-ia
    ports:
      - "5433:5432"

volumes:
  .postgres-data:
